const pool = require("../db");

if (process.env.NODE_ENV === "production") {
  console.log("No se permite ejecutar seeds en producción");
  process.exit(1);
}

const colaboradoresDisponibles = [
  "colab1@demo.com",
  "colab2@demo.com",
  "colab3@demo.com",
  "colab4@demo.com",
  "colab5@demo.com",
];

const terrenos = [
  {
    email_colaborador: "colab1@demo.com",
    titulo: "Terreno comercial en Tijuana",
    descripcion: "Predio urbano con alta conectividad y potencial comercial en zona fronteriza.",
    precio: 2800000,
    ubicacion: "Tijuana, Baja California",
    tipo: "comercial",
    estado: "aprobado",
    estado_region: "Baja California",
    municipio: "Tijuana",
    colonia: "Zona Urbana Río",
    direccion: "Blvd. Sánchez Taboada 1200",
    codigo_postal: "22010",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "comercial",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: true,
    orden_destacado: 1,
    poligono: [
      [32.5295, -117.0382],
      [32.5301, -117.0373],
      [32.5294, -117.0367],
      [32.5288, -117.0376]
    ],
    centro_lat: 32.5295,
    centro_lng: -117.0375,
    area_m2: 2100,
    perimetro_m: 185
  },
  {
    email_colaborador: "colab2@demo.com",
    titulo: "Terreno industrial en Mexicali",
    descripcion: "Excelente opción para bodega o nave industrial con cercanía a corredor logístico.",
    precio: 3200000,
    ubicacion: "Mexicali, Baja California",
    tipo: "industrial",
    estado: "aprobado",
    estado_region: "Baja California",
    municipio: "Mexicali",
    colonia: "Parque Industrial",
    direccion: "Lote 18, Zona Industrial",
    codigo_postal: "21395",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "industrial",
    negociable: false,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [32.6240, -115.4525],
      [32.6247, -115.4515],
      [32.6239, -115.4508],
      [32.6232, -115.4518]
    ],
    centro_lat: 32.6240,
    centro_lng: -115.4517,
    area_m2: 3600,
    perimetro_m: 250
  },
  {
    email_colaborador: "colab3@demo.com",
    titulo: "Terreno residencial en Hermosillo",
    descripcion: "Terreno habitacional en zona con crecimiento residencial y buena conectividad.",
    precio: 1450000,
    ubicacion: "Hermosillo, Sonora",
    tipo: "residencial",
    estado: "aprobado",
    estado_region: "Sonora",
    municipio: "Hermosillo",
    colonia: "Alta California",
    direccion: "Calle Paseo del Sol 88",
    codigo_postal: "83249",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "residencial",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [29.1038, -110.9740],
      [29.1045, -110.9731],
      [29.1037, -110.9725],
      [29.1030, -110.9734]
    ],
    centro_lat: 29.1038,
    centro_lng: -110.9733,
    area_m2: 1550,
    perimetro_m: 150
  },
  {
    email_colaborador: "colab4@demo.com",
    titulo: "Terreno mixto en Chihuahua",
    descripcion: "Predio con versatilidad para proyecto habitacional y comercial.",
    precio: 1900000,
    ubicacion: "Chihuahua, Chihuahua",
    tipo: "mixto",
    estado: "aprobado",
    estado_region: "Chihuahua",
    municipio: "Chihuahua",
    colonia: "Campestre",
    direccion: "Av. Mirador 450",
    codigo_postal: "31213",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "mixto",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [28.6540, -106.0852],
      [28.6547, -106.0842],
      [28.6539, -106.0836],
      [28.6532, -106.0845]
    ],
    centro_lat: 28.6540,
    centro_lng: -106.0844,
    area_m2: 2000,
    perimetro_m: 170
  },
  {
    email_colaborador: "colab5@demo.com",
    titulo: "Terreno comercial en Ciudad Juárez",
    descripcion: "Excelente visibilidad para desarrollo comercial en zona fronteriza estratégica.",
    precio: 2600000,
    ubicacion: "Ciudad Juárez, Chihuahua",
    tipo: "comercial",
    estado: "aprobado",
    estado_region: "Chihuahua",
    municipio: "Juárez",
    colonia: "Pronaf",
    direccion: "Av. Tecnológico 900",
    codigo_postal: "32310",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "comercial",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: true,
    orden_destacado: 2,
    poligono: [
      [31.7204, -106.4248],
      [31.7210, -106.4239],
      [31.7203, -106.4232],
      [31.7196, -106.4241]
    ],
    centro_lat: 31.7203,
    centro_lng: -106.4240,
    area_m2: 2200,
    perimetro_m: 188
  },
  {
    email_colaborador: "colab1@demo.com",
    titulo: "Terreno industrial en Monterrey",
    descripcion: "Ideal para nave industrial, almacén o inversión logística en el área metropolitana.",
    precio: 4100000,
    ubicacion: "Monterrey, Nuevo León",
    tipo: "industrial",
    estado: "aprobado",
    estado_region: "Nuevo León",
    municipio: "Monterrey",
    colonia: "Industrial",
    direccion: "Av. Félix U. Gómez 3400",
    codigo_postal: "64440",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "industrial",
    negociable: false,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: true,
    orden_destacado: 3,
    poligono: [
      [25.7067, -100.3075],
      [25.7074, -100.3065],
      [25.7066, -100.3058],
      [25.7059, -100.3068]
    ],
    centro_lat: 25.7067,
    centro_lng: -100.3067,
    area_m2: 4200,
    perimetro_m: 300
  },
  {
    email_colaborador: "colab2@demo.com",
    titulo: "Terreno residencial en Saltillo",
    descripcion: "Predio habitacional en zona consolidada con servicios cercanos.",
    precio: 1350000,
    ubicacion: "Saltillo, Coahuila",
    tipo: "residencial",
    estado: "aprobado",
    estado_region: "Coahuila",
    municipio: "Saltillo",
    colonia: "Los González",
    direccion: "Blvd. Colosio 221",
    codigo_postal: "25204",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "residencial",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [25.4386, -100.9776],
      [25.4392, -100.9767],
      [25.4385, -100.9760],
      [25.4379, -100.9769]
    ],
    centro_lat: 25.4386,
    centro_lng: -100.9768,
    area_m2: 1480,
    perimetro_m: 148
  },
  {
    email_colaborador: "colab3@demo.com",
    titulo: "Terreno mixto en Torreón",
    descripcion: "Opción flexible para desarrollo urbano con buen frente y conectividad.",
    precio: 1700000,
    ubicacion: "Torreón, Coahuila",
    tipo: "mixto",
    estado: "aprobado",
    estado_region: "Coahuila",
    municipio: "Torreón",
    colonia: "Residencial del Nazas",
    direccion: "Av. Bravo 600",
    codigo_postal: "27000",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "mixto",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [25.5428, -103.4060],
      [25.5435, -103.4050],
      [25.5427, -103.4043],
      [25.5420, -103.4053]
    ],
    centro_lat: 25.5428,
    centro_lng: -103.4052,
    area_m2: 1900,
    perimetro_m: 170
  },
  {
    email_colaborador: "colab4@demo.com",
    titulo: "Terreno agrícola en Culiacán",
    descripcion: "Predio agrícola con buen acceso carretero y amplio potencial productivo.",
    precio: 980000,
    ubicacion: "Culiacán, Sinaloa",
    tipo: "agricola",
    estado: "aprobado",
    estado_region: "Sinaloa",
    municipio: "Culiacán",
    colonia: "Zona Rural",
    direccion: "Parcela 24",
    codigo_postal: "80300",
    topografia: "semi-plano",
    forma: "irregular",
    tipo_propiedad: "ejidal",
    uso_suelo: "agricola",
    negociable: true,
    escritura: "no",
    estatus_legal: "en_revision",
    gravamen: false,
    destacado: false,
    poligono: [
      [24.8077, -107.3935],
      [24.8085, -107.3924],
      [24.8075, -107.3916],
      [24.8067, -107.3927]
    ],
    centro_lat: 24.8076,
    centro_lng: -107.3926,
    area_m2: 5200,
    perimetro_m: 320
  },
  {
    email_colaborador: "colab5@demo.com",
    titulo: "Terreno turístico en Mazatlán",
    descripcion: "Predio con alto potencial para desarrollo vacacional o de servicios.",
    precio: 2950000,
    ubicacion: "Mazatlán, Sinaloa",
    tipo: "comercial",
    estado: "aprobado",
    estado_region: "Sinaloa",
    municipio: "Mazatlán",
    colonia: "Marina Mazatlán",
    direccion: "Av. Sábalo Cerritos 1200",
    codigo_postal: "82112",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "comercial",
    negociable: false,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [23.2818, -106.4658],
      [23.2825, -106.4648],
      [23.2817, -106.4641],
      [23.2810, -106.4651]
    ],
    centro_lat: 23.2818,
    centro_lng: -106.4649,
    area_m2: 2300,
    perimetro_m: 192
  },
  {
    email_colaborador: "colab1@demo.com",
    titulo: "Terreno residencial en Guadalajara",
    descripcion: "Predio ideal para vivienda en zona urbana con alta demanda.",
    precio: 2100000,
    ubicacion: "Guadalajara, Jalisco",
    tipo: "residencial",
    estado: "aprobado",
    estado_region: "Jalisco",
    municipio: "Guadalajara",
    colonia: "Providencia",
    direccion: "Av. Pablo Neruda 780",
    codigo_postal: "44630",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "residencial",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [20.6906, -103.3925],
      [20.6913, -103.3915],
      [20.6905, -103.3908],
      [20.6898, -103.3918]
    ],
    centro_lat: 20.6906,
    centro_lng: -103.3916,
    area_m2: 1700,
    perimetro_m: 160
  },
  {
    email_colaborador: "colab2@demo.com",
    titulo: "Terreno comercial en Aguascalientes",
    descripcion: "Ubicación con visibilidad y cercanía a corredores de crecimiento urbano.",
    precio: 1600000,
    ubicacion: "Aguascalientes, Aguascalientes",
    tipo: "comercial",
    estado: "aprobado",
    estado_region: "Aguascalientes",
    municipio: "Aguascalientes",
    colonia: "San Telmo",
    direccion: "Av. Universidad 1500",
    codigo_postal: "20130",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "comercial",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [21.8963, -102.3090],
      [21.8969, -102.3081],
      [21.8962, -102.3075],
      [21.8956, -102.3084]
    ],
    centro_lat: 21.8963,
    centro_lng: -102.3082,
    area_m2: 1850,
    perimetro_m: 168
  },
  {
    email_colaborador: "colab3@demo.com",
    titulo: "Terreno residencial en León",
    descripcion: "Predio habitacional bien ubicado para pruebas en zona Bajío.",
    precio: 1320000,
    ubicacion: "León, Guanajuato",
    tipo: "residencial",
    estado: "aprobado",
    estado_region: "Guanajuato",
    municipio: "León",
    colonia: "Punta del Este",
    direccion: "Circuito del Lago 89",
    codigo_postal: "37295",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "residencial",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [21.0922, -101.6210],
      [21.0929, -101.6202],
      [21.0921, -101.6195],
      [21.0914, -101.6203]
    ],
    centro_lat: 21.0921,
    centro_lng: -101.6202,
    area_m2: 1600,
    perimetro_m: 154
  },
  {
    email_colaborador: "colab4@demo.com",
    titulo: "Terreno mixto en Querétaro",
    descripcion: "Predio apto para proyecto urbano de uso mixto en ciudad estratégica.",
    precio: 2400000,
    ubicacion: "Querétaro, Querétaro",
    tipo: "mixto",
    estado: "aprobado",
    estado_region: "Querétaro",
    municipio: "Querétaro",
    colonia: "Juriquilla",
    direccion: "Blvd. Universitario 420",
    codigo_postal: "76230",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "mixto",
    negociable: false,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: true,
    orden_destacado: 4,
    poligono: [
      [20.7032, -100.4437],
      [20.7039, -100.4428],
      [20.7031, -100.4421],
      [20.7024, -100.4430]
    ],
    centro_lat: 20.7032,
    centro_lng: -100.4429,
    area_m2: 2500,
    perimetro_m: 195
  },
  {
    email_colaborador: "colab5@demo.com",
    titulo: "Terreno industrial en San Luis Potosí",
    descripcion: "Zona ideal para pruebas logísticas y de parques industriales en el centro-norte.",
    precio: 2900000,
    ubicacion: "San Luis Potosí, San Luis Potosí",
    tipo: "industrial",
    estado: "aprobado",
    estado_region: "San Luis Potosí",
    municipio: "San Luis Potosí",
    colonia: "Zona Industrial",
    direccion: "Eje 128 500",
    codigo_postal: "78395",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "industrial",
    negociable: false,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [22.1266, -100.9160],
      [22.1274, -100.9150],
      [22.1265, -100.9143],
      [22.1257, -100.9153]
    ],
    centro_lat: 22.1266,
    centro_lng: -100.9152,
    area_m2: 3300,
    perimetro_m: 245
  },
  {
    email_colaborador: "colab1@demo.com",
    titulo: "Terreno comercial en Ciudad de México",
    descripcion: "Predio urbano de alto valor estratégico para pruebas en el centro del país.",
    precio: 5200000,
    ubicacion: "Ciudad de México, CDMX",
    tipo: "comercial",
    estado: "aprobado",
    estado_region: "Ciudad de México",
    municipio: "Miguel Hidalgo",
    colonia: "Polanco",
    direccion: "Av. Ejército Nacional 800",
    codigo_postal: "11520",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "comercial",
    negociable: false,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: true,
    orden_destacado: 5,
    poligono: [
      [19.4378, -99.2034],
      [19.4385, -99.2024],
      [19.4377, -99.2017],
      [19.4370, -99.2027]
    ],
    centro_lat: 19.4378,
    centro_lng: -99.2025,
    area_m2: 2600,
    perimetro_m: 205
  },
  {
    email_colaborador: "colab2@demo.com",
    titulo: "Terreno residencial en Puebla",
    descripcion: "Terreno habitacional para pruebas de zona centro-oriente.",
    precio: 1420000,
    ubicacion: "Puebla, Puebla",
    tipo: "residencial",
    estado: "aprobado",
    estado_region: "Puebla",
    municipio: "Puebla",
    colonia: "Lomas de Angelópolis",
    direccion: "Boulevard Europa 240",
    codigo_postal: "72830",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "residencial",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [19.0172, -98.2678],
      [19.0179, -98.2669],
      [19.0171, -98.2662],
      [19.0164, -98.2671]
    ],
    centro_lat: 19.0172,
    centro_lng: -98.2670,
    area_m2: 1500,
    perimetro_m: 149
  },
  {
    email_colaborador: "colab3@demo.com",
    titulo: "Terreno comercial en Veracruz",
    descripcion: "Predio con potencial de servicios y comercio en importante ciudad portuaria.",
    precio: 1850000,
    ubicacion: "Veracruz, Veracruz",
    tipo: "comercial",
    estado: "aprobado",
    estado_region: "Veracruz",
    municipio: "Veracruz",
    colonia: "Boca del Río Centro",
    direccion: "Blvd. Ruiz Cortines 1440",
    codigo_postal: "94290",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "comercial",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [19.1410, -96.1064],
      [19.1417, -96.1055],
      [19.1409, -96.1048],
      [19.1402, -96.1057]
    ],
    centro_lat: 19.1410,
    centro_lng: -96.1056,
    area_m2: 1880,
    perimetro_m: 170
  },
  {
    email_colaborador: "colab4@demo.com",
    titulo: "Terreno residencial en Mérida",
    descripcion: "Predio en ciudad estratégica del sureste para pruebas regionales.",
    precio: 1380000,
    ubicacion: "Mérida, Yucatán",
    tipo: "residencial",
    estado: "aprobado",
    estado_region: "Yucatán",
    municipio: "Mérida",
    colonia: "Temozón Norte",
    direccion: "Calle 20 300",
    codigo_postal: "97302",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "residencial",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [21.0378, -89.6177],
      [21.0385, -89.6168],
      [21.0377, -89.6161],
      [21.0370, -89.6170]
    ],
    centro_lat: 21.0378,
    centro_lng: -89.6169,
    area_m2: 1520,
    perimetro_m: 150
  },
  {
    email_colaborador: "colab5@demo.com",
    titulo: "Terreno turístico en Cancún",
    descripcion: "Excelente ubicación para pruebas en zona turística del Caribe mexicano.",
    precio: 3600000,
    ubicacion: "Cancún, Quintana Roo",
    tipo: "comercial",
    estado: "aprobado",
    estado_region: "Quintana Roo",
    municipio: "Benito Juárez",
    colonia: "Zona Hotelera",
    direccion: "Blvd. Kukulcán Km 12",
    codigo_postal: "77500",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "comercial",
    negociable: false,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: true,
    orden_destacado: 6,
    poligono: [
      [21.1215, -86.7552],
      [21.1222, -86.7542],
      [21.1214, -86.7535],
      [21.1207, -86.7545]
    ],
    centro_lat: 21.1215,
    centro_lng: -86.7544,
    area_m2: 2400,
    perimetro_m: 198
  },
  {
    email_colaborador: "colab1@demo.com",
    titulo: "Terreno mixto en Tuxtla Gutiérrez",
    descripcion: "Predio urbano para pruebas de cobertura en el sureste continental.",
    precio: 1280000,
    ubicacion: "Tuxtla Gutiérrez, Chiapas",
    tipo: "mixto",
    estado: "aprobado",
    estado_region: "Chiapas",
    municipio: "Tuxtla Gutiérrez",
    colonia: "Mactumatzá",
    direccion: "Calzada al Sumidero 210",
    codigo_postal: "29000",
    topografia: "semi-plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "mixto",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [16.7470, -93.1025],
      [16.7477, -93.1016],
      [16.7469, -93.1009],
      [16.7462, -93.1018]
    ],
    centro_lat: 16.7470,
    centro_lng: -93.1017,
    area_m2: 1750,
    perimetro_m: 162
  },
  {
    email_colaborador: "colab2@demo.com",
    titulo: "Terreno residencial en Oaxaca",
    descripcion: "Predio con ubicación estratégica para pruebas en el sur del país.",
    precio: 1190000,
    ubicacion: "Oaxaca de Juárez, Oaxaca",
    tipo: "residencial",
    estado: "aprobado",
    estado_region: "Oaxaca",
    municipio: "Oaxaca de Juárez",
    colonia: "Reforma",
    direccion: "Calzada Porfirio Díaz 520",
    codigo_postal: "68050",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "residencial",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [17.0733, -96.7218],
      [17.0740, -96.7209],
      [17.0732, -96.7202],
      [17.0725, -96.7211]
    ],
    centro_lat: 17.0733,
    centro_lng: -96.7210,
    area_m2: 1450,
    perimetro_m: 146
  },
  {
    email_colaborador: "colab3@demo.com",
    titulo: "Terreno comercial en Acapulco",
    descripcion: "Predio para pruebas en corredor turístico del Pacífico sur.",
    precio: 2100000,
    ubicacion: "Acapulco, Guerrero",
    tipo: "comercial",
    estado: "aprobado",
    estado_region: "Guerrero",
    municipio: "Acapulco de Juárez",
    colonia: "Costera",
    direccion: "Av. Costera Miguel Alemán 1800",
    codigo_postal: "39670",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "comercial",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [16.8531, -99.8730],
      [16.8538, -99.8721],
      [16.8530, -99.8714],
      [16.8523, -99.8723]
    ],
    centro_lat: 16.8531,
    centro_lng: -99.8722,
    area_m2: 2050,
    perimetro_m: 178
  },
  {
    email_colaborador: "colab4@demo.com",
    titulo: "Terreno mixto en Villahermosa",
    descripcion: "Predio urbano para pruebas en la zona del golfo-sureste.",
    precio: 1490000,
    ubicacion: "Villahermosa, Tabasco",
    tipo: "mixto",
    estado: "aprobado",
    estado_region: "Tabasco",
    municipio: "Centro",
    colonia: "Tabasco 2000",
    direccion: "Paseo Usumacinta 900",
    codigo_postal: "86035",
    topografia: "plano",
    forma: "regular",
    tipo_propiedad: "privada",
    uso_suelo: "mixto",
    negociable: true,
    escritura: "si",
    estatus_legal: "regular",
    gravamen: false,
    destacado: false,
    poligono: [
      [17.9898, -92.9287],
      [17.9905, -92.9278],
      [17.9897, -92.9271],
      [17.9890, -92.9280]
    ],
    centro_lat: 17.9898,
    centro_lng: -92.9279,
    area_m2: 1820,
    perimetro_m: 168
  }
];

const seedTerrenos = async () => {
  try {
    for (const terreno of terrenos) {
      const userResult = await pool.query(
        `SELECT id, rol
         FROM usuarios
         WHERE email = $1
         LIMIT 1`,
        [terreno.email_colaborador]
      );

      if (userResult.rows.length === 0) {
        console.log(`No existe usuario: ${terreno.email_colaborador}`);
        continue;
      }

      const usuario = userResult.rows[0];

      if (usuario.rol !== "colaborador") {
        console.log(`El usuario no es colaborador: ${terreno.email_colaborador}`);
        continue;
      }

      const existe = await pool.query(
        `SELECT id
         FROM terrenos
         WHERE titulo = $1 AND usuario_id = $2
         LIMIT 1`,
        [terreno.titulo, usuario.id]
      );

      if (existe.rows.length > 0) {
        console.log(`Ya existe terreno: ${terreno.titulo}`);
        continue;
      }

      const destacadoDesde = terreno.destacado ? new Date() : null;

      await pool.query(
        `
        INSERT INTO terrenos (
          titulo,
          descripcion,
          precio,
          ubicacion,
          tipo,
          creado_en,
          poligono,
          usuario_id,
          estado,
          centro_lat,
          centro_lng,
          area_m2,
          perimetro_m,
          estado_region,
          municipio,
          colonia,
          direccion,
          codigo_postal,
          topografia,
          forma,
          tipo_propiedad,
          uso_suelo,
          negociable,
          actualizado_en,
          escritura,
          estatus_legal,
          gravamen,
          destacado,
          orden_destacado,
          destacado_desde,
          destacado_hasta
        )
        VALUES (
          $1, $2, $3, $4, $5, NOW(), $6::jsonb, $7, $8, $9, $10,
          $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21,
          $22, NOW(), $23, $24, $25, $26, $27, $28, $29
        )
        `,
        [
          terreno.titulo,
          terreno.descripcion,
          terreno.precio,
          terreno.ubicacion,
          terreno.tipo,
          JSON.stringify(terreno.poligono),
          usuario.id,
          terreno.estado,
          terreno.centro_lat,
          terreno.centro_lng,
          terreno.area_m2,
          terreno.perimetro_m,
          terreno.estado_region,
          terreno.municipio,
          terreno.colonia,
          terreno.direccion,
          terreno.codigo_postal,
          terreno.topografia,
          terreno.forma,
          terreno.tipo_propiedad,
          terreno.uso_suelo,
          terreno.negociable,
          terreno.escritura,
          terreno.estatus_legal,
          terreno.gravamen,
          terreno.destacado,
          terreno.orden_destacado || null,
          destacadoDesde,
          null
        ]
      );

      console.log(`Terreno creado: ${terreno.titulo} -> ${terreno.email_colaborador}`);
    }

    console.log("Seed de terrenos completado");
    await pool.end();
    process.exit(0);
  } catch (error) {
    console.error("Error en seedTerrenos:", error);
    await pool.end();
    process.exit(1);
  }
};

seedTerrenos();